//
//  NewsStore.swift
//  AppDesign
//
//  Created by Singh, Akash | RIEPL on 06/11/22.
//

import Foundation

struct NewsStore {
    static let shared = NewsStore()
    
    func getAll() -> [News]{
        // images are downloaded from canva (allow for commercial use)
        let description = "A news application is a big interactive database that tells a news story. Think of it like you would any other piece of journalism. It just uses software instead of words and pictures. By showing each reader data that is specific to them, a news app can help each reader understand a story in a way that’s personally meaningful to them. It can help a reader understand their personal connection to a broad national phenomenon, and help them attach what they know to what they don’t know, and thereby encourage a deep understanding of abstract concepts."
        return [
            News(id: UUID().uuidString, title: "ICC T20 World Cup", description: "The triple-header on Sunday began with a shock loss for South Africa, who exited the tournament to open the gates for Pakistan or Bangladesh to qualify. At the same venue, Pakistan beat Bangladesh to seal their semi-final spot. With New Zealand and England having already sealed their qualification after Saturday's round of matches, Group 2 witnessed some drama with the Proteas going down to Netherlands in a stunning loss for the Temba Bavuma-led side, who were once on top of the table before back-to-back losses against Pakistan and Netherlands.", dateString: "November 3, 2022", author: "John Smith", imageName: "worldcup"),
            News(id: UUID().uuidString, title: "Ind VS Pak", description: "South Africa’s shocking defeat against the Netherlands has kicked the Proteas out of the T20 World Cup 2022. There are two things that may seem significant for Indian fans after the result of the South Africa vs Netherlands match. Firstly, India have now secured its place in the semi-finals. The result of the India vs Zimbabwe match later in the day will only make sure Rohit Sharma’s boys will end up on top of the group or not.", dateString: "November 4, 2022", author: "John Smith", imageName: "indvspak"),
            News(id: UUID().uuidString, title: "India at UN", description: "Prime Minister Shri Narendra Modi spoke on phone with President of the Russian Federation H.E. Mr. Vladimir Putin on 2 July 2020. Prime Minister warmly congratulated President Putin on the success of celebrations marking the 75th anniversary of the victory in the Second World War, and also for successful completion of the vote on constitutional amendments in Russia. Prime Minister recalled the participation of an Indian contingent in the military parade held in Moscow on 24 June 2020, as a symbol of abiding friendship between the peoples of India and Russia.", dateString: "November 5, 2022", author: "Alan Delloit", imageName: "un"),
            News(id: UUID().uuidString, title: "Top 5 Economies", description: "Gross domestic product (GDP) is an estimate of the total value of finished goods and services produced within a country’s borders during a specified period, usually a year. GDP is popularly used to estimate the size of a country’s economy. GDP is most commonly measured by using the expenditure method, which calculates GDP by adding up spending on new consumer goods, new investment spending, government spending, and the value of net exports (exports minus imports).", dateString: "October 12, 2022", author: "John Smith", imageName: "economy"),
            News(id: UUID().uuidString, title: "Best foods for weight loss", description: "Protein fills you up quickly and keeps you full for a long time. It also decreases post-meal secretions of the hunger hormone ghrelin, thus reducing feelings of hunger, says Dr. Olesiak. Protein also takes more energy to digest and increases lean muscle mass, both of which help boost metabolism,” he says. Dietary fiber slows digestion and ensures a gradual rise in blood glucose levels, which triggers a slower release of the fat-storage hormone insulin, explains Dr. Olesiak. As fiber moves through the digestive system, various satiety hormones (like ghrelin) are released, sending signals to the brain to reduce hunger and regulate food intake,” he says.", dateString: "November 3, 2022", author: "Rosse M. S.", imageName: "food"),
            News(id: UUID().uuidString, title: "Latest technology trends", description: "Technology today is evolving at a rapid pace, enabling faster change and progress, causing an acceleration of the rate of change. However, it is not only technology trends and emerging technologies that are evolving, a lot more has changed this year due to the outbreak of COVID-19 making IT professionals realize that their role will not stay the same in the contactless world tomorrow. And an IT professional in 2023-24 will constantly be learning, unlearning, and relearning (out of necessity if not desire).", dateString: "October 3, 2022", author: "John Smith", imageName: "tech"),
            News(id: UUID().uuidString, title: "World cup campaign : India", description: "India will open their 2022 T20 World Cup campaign with a blockbuster tie against Pakistan at the iconic Melbourne Cricket Ground on October 23 this year as the International Cricket Council on Friday announced the schedule for the 2022 T20 World Cup.", dateString: "November 4, 2022", author: "John Smith", imageName: "india"),
            News(id: UUID().uuidString, title: "Welcome to News app", description: description, dateString: "October 5, 2022", author: "John Smith", imageName: "news")
        ]
    }
}
